version: '{build}'
image: Visual Studio 2017

environment:
  matrix:
  # Available python versions and their locations on https://www.appveyor.com/docs/build-environment/#python
  - PYTHON: C:\Python27-x64
    TOXENV: py27
  - PYTHON: C:\Python35-x64
    TOXENV: py35
  - PYTHON: C:\Python36-x64
    TOXENV: py36

build: off

install:
- cmd: SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%
- cmd: pip install tox

before_test:
- cmd: python --version
- cmd: pip --version
- cmd: tox --version

test_script:
- cmd: >-
    tox
