language: python
os: linux

python: "3.7"

jobs:
  include:
  - python: "2.7"
  - python: "3.7"
    env: PUBLISH_COVERAGE=y
  - env: TOXENV=docs
  - env: TOXENV=pre-commit
  - env: TOXENV=benchmark
  - env: TOXENV=mypy
  allow_failures:
  - env: TOXENV=benchmark
  fast_finish: true

install: pip install tox tox-travis coveralls
script: tox
after_success: |
  if [ "${PUBLISH_COVERAGE:-n}" == "y" ]; then coveralls; fi
  if [ "${TOXENV}" == "benchmark" ]; then
    echo $(ls .benchmarks/*/0001_benchmark.json) $(cat .benchmarks/*/0001_benchmark.json | nc termbin.com 9999)
  fi
